# Generated by Django 4.2.6 on 2024-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEasyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('cpassword', models.CharField(max_length=15)),
            ],
        ),
    ]
