# Generated by Django 4.2.6 on 2024-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolEasy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('DOB', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=125)),
                ('Qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
