# Generated by Django 4.2.6 on 2024-01-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolEasy_app', '0002_studentregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolEasyRegister',
        ),
    ]
